[package]
name = "rushia"
version = "0.1.1"
authors = ["Yuki Okushi <huyuumi.dev@gmail.com>"]
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
