name: Continuous Integration

on:
  schedule:
    # Run at 00:00 UTC every 1st of the month
    - cron: '00 00 01 * *'
  # Allow manually starting the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure rustup
        run: |
          rustup set profile minimal
          rustup override set stable

      - name: cargo run
        run: cargo run -p ajimu
