name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure rustup
        run: |
          rustup set profile minimal
          rustup override set stable

      - name: cargo check
        run: cargo check --workspace

      - name: clippy
        run: |
          rustup component add clippy
          cargo clippy --workspace -- --deny warnings
